// Generated by https://quicktype.io

export interface SaveWorkoutRequest {
  id: string;
  exercises: WorkoutRequestExercise[];
}

export interface WorkoutRequestExercise {
  routineExerciseId: string;
  setsCompleted: number;
  repsCompleted: number;
  weightUsed: number;
  restTime: number;
}
