// Generated by https://quicktype.io

export interface FindOneExerciseResponse {
  id: string;
  name: string;
  description: string;
  difficultyLevel: string;
  relativeLoad: number;
  stabilityRequirement: number;
  rangeOfMotion: number;
  technicalDemand: number;
  images: any[];
  muscleActivations: MuscleActivation[];
}

export interface MuscleActivation {
  muscleName: string;
  activationLevel: number;
}
